/**
 * Referensi geografi Indonesia untuk saran lokasi (form unggah, filter).
 * Dipakai sebagai PELENGKAP lokasi yang sudah dipakai di DB (diurut sesudah
 * yang populer), bukan pengganti — dieja resmi, tanpa singkatan.
 *
 * Sumber: pembagian administratif 38 provinsi + kota & destinasi populer.
 * Bukan dari geocoding live (Nominatim butuh 1 req/detik + atribusi +
 * jaringan) — daftar statis selalu tersedia, instan, dan konsisten.
 */
export const INDONESIA_PLACES: string[] = [
  // ── 38 provinsi ──
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Kepulauan Riau",
  "Jambi",
  "Sumatera Selatan",
  "Kepulauan Bangka Belitung",
  "Bengkulu",
  "Lampung",
  "Banten",
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Gorontalo",
  "Sulawesi Tengah",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
  "Papua Tengah",
  "Papua Pegunungan",
  "Papua Selatan",
  "Papua Barat Daya",
  // ── kota besar ──
  "Jakarta",
  "Surabaya",
  "Bandung",
  "Medan",
  "Semarang",
  "Palembang",
  "Makassar",
  "Denpasar",
  "Yogyakarta",
  "Surakarta",
  "Malang",
  "Bogor",
  "Depok",
  "Tangerang",
  "Bekasi",
  "Bandar Lampung",
  "Padang",
  "Pekanbaru",
  "Banjarmasin",
  "Pontianak",
  "Samarinda",
  "Balikpapan",
  "Manado",
  "Palu",
  "Kendari",
  "Ambon",
  "Jayapura",
  "Mataram",
  "Kupang",
  "Banda Aceh",
  "Serang",
  "Cilegon",
  "Tasikmalaya",
  "Cirebon",
  "Purwokerto",
  "Magelang",
  "Kediri",
  "Jember",
  "Banyuwangi",
  "Probolinggo",
  "Pasuruan",
  "Blitar",
  "Madiun",
  "Batu",
  "Sukabumi",
  "Garut",
  "Lembang",
  "Puncak",
  "Pangandaran",
  "Anyer",
  "Bukittinggi",
  "Payakumbuh",
  "Dumai",
  "Tanjung Pinang",
  "Batam",
  "Pangkal Pinang",
  "Tanjung Pandan",
  "Singkawang",
  "Palangka Raya",
  "Tarakan",
  "Bitung",
  "Tomohon",
  "Mamuju",
  "Parepare",
  "Palopo",
  "Tana Toraja",
  "Bau-Bau",
  "Ternate",
  "Tidore",
  "Sorong",
  "Manokwari",
  "Merauke",
  "Wamena",
  "Timika",
  "Biak",
  // ── destinasi populer ──
  "Danau Toba",
  "Samosir",
  "Bukit Lawang",
  "Nias",
  "Sabang",
  "Weh",
  "Belitung",
  "Kepulauan Seribu",
  "Ujung Kulon",
  "Borobudur",
  "Prambanan",
  "Dieng",
  "Baturaden",
  "Karimunjawa",
  "Malioboro",
  "Parangtritis",
  "Gunungkidul",
  "Bromo",
  "Semeru",
  "Ijen",
  "Ubud",
  "Canggu",
  "Uluwatu",
  "Tanah Lot",
  "Nusa Penida",
  "Nusa Lembongan",
  "Gili Trawangan",
  "Gili Air",
  "Gili Meno",
  "Lombok",
  "Rinjani",
  "Komodo",
  "Labuan Bajo",
  "Wae Rebo",
  "Kelimutu",
  "Sumba",
  "Alor",
  "Lembata",
  "Flores",
  "Derawan",
  "Maratua",
  "Bunaken",
  "Likupang",
  "Wakatobi",
  "Bira",
  "Tanjung Bira",
  "Raja Ampat",
  "Wayag",
  "Piaynemo",
  "Banda Neira",
  "Ora Beach",
  "Togean",
  "Bangka Belitung",
  "Karimata",
  "Anambas",
  "Natuna",
  "Bintan",
  "Lingga",
];
